### PR TITLE
Complete rebuild of ode_csv2shapefile.py

### LINKED ISSUE #74: ode_get_laser_alt.py: Add main()
The `ode_get_laser_alt.py` script has a number of functions defined at the top but the main functionality is just floating below these definitions. This should be moved inside a `main()` function following Python best practices.

### LINKED ISSUE #75: ode_csv2shapefile.py: Add main()
The `ode_csv2shapefile.py` script has a number of functions defined at the top but the main functionality is just floating below these definitions. This should be moved inside a `main()` function following Python best practices.

### LINKED ISSUE #76: ode_csv2shapefile.py: Build VRT using `xml.etree.ElementTree ` Instead of Manually Printing Strings
https://github.com/USGS-Astrogeology/APPL-Tools/blob/9e6eeab4ea1aa845688db9100ddb6ef0789f0fba/Workflow_Scripts/ode_csv2shapefile.py#L241-L257

Building VRTs as intermediaries to convert tabular data to shapefiles is kind of a pain, but sometimes we have to do it. We can make this process slightly more elegant in `ode_csv2shapefile.py` by building VRTs programmatically (treating them as XML-formatted files, which they are) rather than printing strings manually to a file one line at a time.

An example of how to do this for MOLA PEDR files is in [pedr.py](https://github.com/USGS-Astrogeology/APPL-Tools/blob/9e6eeab4ea1aa845688db9100ddb6ef0789f0fba/appl_tools/pedr.py#L135). It may even be possible to use the existing `pedrcsv2shp()` in  `ode_csv2shapefile.py` (even though the function name will be a bit of a misnomer).

### PR DESCRIPTION
**Pull request by dpmayerUSGS**
- Rebuilt `ode_csv2shapefile.py` with  cleaner commandline. 
  - Put core functionality inside `main()` (Fixes #75 )
  - Build VRT using XML ETree instead of manually formatting strings (Fixes #76 )
  - Optionally supports ographic latitudes (Mars only), 
  - Optionally supports heights relative to geoid (Mars or Moon), default Z values are heights relative to IAU sphere for the body (or IAU ellipsoid if Mars and `--ographic` passed)
  - By default outputs shapefile with Geographic 2D CRS
    - new option `--force-3d` will override PROJ and force pseudo-ESRI WKT1 of geographic 3D CRS for use in GXP
    - with or without `--force-3d`, geometry type of the output shapefile is always "3D Point," so a GIS will recognize Z values
  - User can specify 1 or more input files without setting special flags
- `ode_get_laser_alt.py`
  - Cleaned up argument parsing and added docstrings
  - Put core functionality inside `main()` (Fixes #74 )

- Removed extraneous comments or debugging code from a few other scripts that I forgot to remove previously.

### CODE REVIEW

**Comment by thareUSGS** [comment]
looks good thus far. Testing now.

**Comment by thareUSGS** [comment]
Can line 235 be updated from
`r = requests.get(fileurl, stream=True)`
to
`r = requests.get(fileurl, stream=True,  verify=False)`

I am always getting an '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)'

**Comment by thareUSGS** [comment]
simply running doesn't exit gracefully with a warning? Can/should  it?

> python ode_get_laser_alt.py
```
Namespace(mode=None)
Submitting query. Please wait...
Traceback (most recent call last):
  File "ode_get_laser_alt.py", line 363, in <module>
    sys.exit(main(parse_args()))
  File "ode_get_laser_alt.py", line 295, in main
    r = requests.get('http://oderest.rsl.wustl.edu/livegds', params=payload)
UnboundLocalError: local variable 'payload' referenced before assignment

```

**Comment by dpmayerUSGS** [comment]
@thareUSGS That's a config issue on the user side. Users should be responsible for making sure their security certificates are correct/up to date. In general, it's not a good idea fpr a script to force a user to use an insecure method of downloading files without their explicit permission.

**Comment by dpmayerUSGS** [comment]
> simply running doesn't exit gracefully with a warning? Can/should it?

That looks like a bug to me. Running without any args should print the argparse help and exit cleanly.

**Comment by thareUSGS** [comment]
optional:  Back to back runs leads to different parameters needed. Can we just emulate the first run paramters into the second. FOr example

 > python ode_get_laser_alt.py target mars --raster testdata/Mawrth_Vallis_3413E_242N_mola.cub
and then
 > python ode_csv2shapefile.py mars MolaPEDR_24N25N_341E342E_20210709T130050720_pts_csv.csv

to be consistent should have the ode_csv2shapefile.py be something like:

 > python ode_csv2shapefile.py **target** mars **--csv** MolaPEDR_24N25N_341E342E_20210709T130050720_pts_csv.csv

**Comment by dpmayerUSGS** [comment]
@thareUSGS The reason there are 2 scripts in the first place is based on the assumption that the scripts will not *necessarily* be run back to back, either (1) because the user isn't interested in converting to shapefile, (2) because they've opted to run `ode_get_laser_alt.py` with `--async` or (3) because (in the case of MLA data) they are *required* to run with the `--async` flag, and may then run in `status` mode to check if the file is ready/download it when it is.

The use of the `target` and `status` keywords in `ode_get_laser_alt.py` is necessary to indicate to the argument parser which of the 2 modes the script should run in. This obviously isn't needed for `ode_csv2shapefile.py`. I don't like the idea of adding an unnecessary parameter ("target") to a script. `ode_csv2shapefile.py` is capable of treating the first positional parameter as the name of a target without making the user type the word "target."

An alternative is to scrap the `status` mode so that the argument parser can be simplified such that the user doesn't need to indicate `target` on the commandline. We could then make an optional argument `--status` that takes a jobID as a single argument, and then inside `main()` we could check if that option was passed and ignore everything else that a user may have passed on the commandline. I prefer to let `argparse` sanity check the commandline arguments rather than doing it in `main()`, but this particular solution wouldn't be too difficult to implement.

I'm opposed to adding the `--csv <filename>` convention you suggest because I'm trying to follow the principle that positional parameters are required and dash arguments are optional. An input CSV is naturally required by `ode_csv2shapefile.py. Think of it like `gdal_translate <options> <in_ds> <out_ds>`

**Comment by thareUSGS** [comment]
I am fine with that. That is all I got -- feel free to merge.

**Pull request merged**
